# Lecture 6

# Pandas

In [ ]:
import numpy as np
import pandas as pd

from google.colab import data_table
data_table.enable_dataframe_formatter()

## Series ops

In [ ]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

In [ ]:
s1.values

array([1, 2, 3])

In [ ]:
s2.values

array([4, 5, 6])

In [ ]:
s1.values + s2.values

array([5, 7, 9])

In [ ]:
s1 + s2

0    5
1    7
2    9
dtype: int64

In [ ]:
s1 = pd.Series([1, 2], index=[0, 1])
s2 = pd.Series([3, 4], index=[1, 2])

In [ ]:
s1.values + s2.values

array([4, 6])

In [ ]:
s1 + s2

0    NaN
1    5.0
2    NaN
dtype: float64

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

In [ ]:
s1 + s2

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

In [ ]:
s1 + s2

a    NaN
b    6.0
c    8.0
c    9.0
dtype: float64

In [ ]:
s1.reset_index(drop=True) + s2.reset_index(drop=True)

0    5
1    7
2    9
dtype: int64

In [ ]:
s1 + s2

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0)

a    1.0
b    6.0
c    8.0
d    6.0
dtype: float64

## Concat Series

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([4, 5], index=['b', 'c'])

In [ ]:
pd.concat([s1, s2])

a    1
b    2
c    3
b    4
c    5
dtype: int64

In [ ]:
pd.concat([s1, s2], axis=1)

0    1
a  1  NaN
b  2  4.0
c  3  5.0

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'], name='col1')
s2 = pd.Series([4, 5, 6], index=['x', 'y', 'z'], name='col2')

In [ ]:
pd.concat([s1, s2])

a    1
b    2
c    3
x    4
y    5
z    6
dtype: int64

In [ ]:
pd.concat([s1, s2], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
pd.concat([s1, s2], axis=1)

col1  col2
a   1.0   NaN
b   2.0   NaN
c   3.0   NaN
x   NaN   4.0
y   NaN   5.0
z   NaN   6.0

In [ ]:
pd.concat([s1, s2], axis=1, ignore_index=True)

0    1
a  1.0  NaN
b  2.0  NaN
c  3.0  NaN
x  NaN  4.0
y  NaN  5.0
z  NaN  6.0

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'], name='col1')
s2 = pd.Series([4, 5, 6], index=['x', 'y', 'z'], name='col1')

In [ ]:
pd.concat([s1, s2])

In [ ]:
pd.concat([s1, s2], ignore_index=True)

In [ ]:
pd.concat([s1, s2], axis=1)

In [ ]:
pd.concat([s1, s2], axis=1, ignore_index=True)

## Merge Series

In [ ]:
s1 = pd.Series([2, 3, 4], index=['a', 'b', 'c'], name='Col1')
s2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'], name='Col2')

In [ ]:
s1

a    2
b    3
c    4
Name: Col1, dtype: int64

In [ ]:
s2

b    4
c    5
d    6
Name: Col2, dtype: int64

In [ ]:
pd.merge(s1, s2, left_index=True, right_index=True, how='outer')

Col1  Col2
a   2.0   NaN
b   3.0   4.0
c   4.0   5.0
d   NaN   6.0

In [ ]:
pd.merge(s1, s2, left_index=True, right_index=True, how='inner')

Col1  Col2
b     3     4
c     4     5

In [ ]:
pd.merge(s1, s2, left_index=True, right_index=True, how='left')

Col1  Col2
a     2   NaN
b     3   4.0
c     4   5.0

In [ ]:
pd.merge(s1, s2, left_index=True, right_index=True, how='right')

Col1  Col2
b   3.0     4
c   4.0     5
d   NaN     6

In [ ]:
pd.merge(s2, s1, left_index=True, right_index=True, how='left')

Col2  Col1
b     4   3.0
c     5   4.0
d     6   NaN

In [ ]:
s1

a    2
b    3
c    4
Name: Col1, dtype: int64

In [ ]:
s2

b    4
c    5
d    6
Name: Col2, dtype: int64

In [ ]:
pd.merge(s1, s2, left_on='Col1', right_on='Col2', how='outer')

Col1  Col2
0   2.0   NaN
1   3.0   NaN
2   4.0   4.0
3   NaN   5.0
4   NaN   6.0

In [ ]:
pd.merge(s1, s2, left_on='Col1', right_on='Col2', how='inner')

Col1  Col2
0     4     4

In [ ]:
pd.merge(s1, s2, left_on='Col1', right_on='Col2', how='left')

Col1  Col2
0     2   NaN
1     3   NaN
2     4   4.0

In [ ]:
pd.merge(s1, s2, left_on='Col1', right_on='Col2', how='right')

Col1  Col2
0   4.0     4
1   NaN     5
2   NaN     6

## Merge DataFrames

In [ ]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value1': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['B', 'C', 'D'], 'value2': [4, 5, 6]})

In [ ]:
df1

key  value1
0   A       1
1   B       2
2   C       3

In [ ]:
df2

key  value2
0   B       4
1   C       5
2   D       6

In [ ]:
pd.merge(df1, df2, left_on='key', right_on='key', how='outer')

key  value1  value2
0   A     1.0     NaN
1   B     2.0     4.0
2   C     3.0     5.0
3   D     NaN     6.0

In [ ]:
pd.merge(df1, df2, on='key', how='outer')

key  value1  value2
0   A     1.0     NaN
1   B     2.0     4.0
2   C     3.0     5.0
3   D     NaN     6.0

In [ ]:
pd.merge(df1, df2, left_on='key', right_on='key', how='inner')

key  value1  value2
0   B       2       4
1   C       3       5

In [ ]:
pd.merge(df1, df2, left_on='key', right_on='key', how='left')

key  value1  value2
0   A       1     NaN
1   B       2     4.0
2   C       3     5.0

In [ ]:
pd.merge(df1, df2, left_on='key', right_on='key', how='right')

key  value1  value2
0   B     2.0       4
1   C     3.0       5
2   D     NaN       6

In [ ]:
df1

key  value1
0   A       1
1   B       2
2   C       3

In [ ]:
df2

key  value2
0   B       4
1   C       5
2   D       6

In [ ]:
pd.merge(df1, df2, how='cross')

key_x  value1 key_y  value2
0     A       1     B       4
1     A       1     C       5
2     A       1     D       6
3     B       2     B       4
4     B       2     C       5
5     B       2     D       6
6     C       3     B       4
7     C       3     C       5
8     C       3     D       6

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='outer')

key_x  value1 key_y  value2
0     A       1     B       4
1     B       2     C       5
2     C       3     D       6

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='inner')

key_x  value1 key_y  value2
0     A       1     B       4
1     B       2     C       5
2     C       3     D       6

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='left')

key_x  value1 key_y  value2
0     A       1     B       4
1     B       2     C       5
2     C       3     D       6

In [ ]:
pd.merge(df1, df2, left_index=True, right_index=True, how='right')

key_x  value1 key_y  value2
0     A       1     B       4
1     B       2     C       5
2     C       3     D       6

## Join DataFrames

In [ ]:
df1 = pd.DataFrame({'value1': [1, 2, 3]}, index=['A', 'B', 'C'])
df2 = pd.DataFrame({'value2': [4, 5, 6]}, index=['B', 'C', 'D'])

In [ ]:
df1.join(df2, how='outer')

value1  value2
A     1.0     NaN
B     2.0     4.0
C     3.0     5.0
D     NaN     6.0

In [ ]:
df1.join(df2, how='inner')

value1  value2
B       2       4
C       3       5

In [ ]:
df1.join(df2, how='left')

value1  value2
A       1     NaN
B       2     4.0
C       3     5.0

In [ ]:
df2.join(df1, how='right')

value2  value1
A     NaN       1
B     4.0       2
C     5.0       3

## Concat Dataframes

In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

In [ ]:
pd.concat([df1, df2])

A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [ ]:
pd.concat([df1, df2], axis=1)

A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
df1 = pd.DataFrame({'A': [1, 2]}, index=['x', 'y'])
df2 = pd.DataFrame({'B': [3, 4]}, index=['y', 'z'])

In [ ]:
pd.concat([df1, df2], axis=1)

| | | |
| --- | --- | --- |
| Feature |	pd.concat() |	pd.merge() |
| Purpose |	Stack or align data vertically/horizontally	| SQL-like joins based on keys or conditions |
| Keys/Conditions |	Not required | Required for merging |
| Index Alignment |	Aligns automatically (or ignores)	| Flexible: Can align by columns, indexes, or conditions |
| Join Types | Outer join for columns (default) |	Supports inner, outer, left, right |
| Flexibility	| Simple stacking/aligning | Highly flexible and feature-rich |

Use pd.concat() for simple concatenation and pd.merge() for more complex, key-based combinations.


In [155]:
a | 'ssa'

TypeError: unsupported operand type(s) for |: 'set' and 'str'

## Group by

In [ ]:
speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 80.2),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)

In [ ]:
speeds

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [150]:
np.random.choice(np.arange(1, 26), 4, replace=False) + np.array([0, 25, 50, 75])

array([20, 35, 55, 97])

In [ ]:
for n, g in speeds.groupby("class"):
  # print(n, '\n', g, '\n\n\n')
  print(n, g.max_speed.mean())

bird 206.5
mammal 69.1


In [ ]:
speeds.groupby("class").max_speed.mean()


class
bird      206.5
mammal     69.1
Name: max_speed, dtype: float64

In [ ]:
speeds.groupby(["class", "order"]).mean()

max_speed
class  order                    
bird   Falconiformes       389.0
       Psittaciformes       24.0
mammal Carnivora            69.1
       Primates              NaN