# Lecture 5 (09 Nov 2024)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kosavina/hse-python-2024/blob/main/Lecture_5.ipynb)

In [ ]:
%%shell
if [ ! -d "data" ]; then
  git clone https://github.com/PacktPublishing/Pandas-Cookbook/
  mv ./Pandas-Cookbook/data/ ./
  rm -R ./Pandas-Cookbook
else
  echo "Skipping clone."
fi

Cloning into 'Pandas-Cookbook'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 118 (delta 9), reused 10 (delta 3), pack-reused 100 (from 1)
Receiving objects: 100% (118/118), 33.40 MiB | 8.22 MiB/s, done.
Resolving deltas: 100% (28/28), done.
Updating files: 100% (70/70), done.


# Numpy Exercises

In [ ]:
import numpy as np

1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List:
``` python
[12.23, 13.32, 100, 36.32]
```

One-dimensional NumPy array:
``` python
[ 12.23 13.32 100. 36.32]
```

In [ ]:
l = [12.23, 13.32, 100, 36.32]

In [ ]:
arr = np.array(l)

In [ ]:
type(arr)

numpy.ndarray

2. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

``` python
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

Update sixth value to 11

``` python
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]
```

In [ ]:
a = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=float)
a[6] = 11

In [ ]:
a = np.zeros(10)
a[6] = 11

3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:
``` python
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]
```

In [ ]:
x = np.array([[ 2, 3, 4], [ 5, 6, 7], [ 8, 9, 10]])
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

4. Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:
``` python
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
```

In [ ]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

5. Write a NumPy program to reverse an array (the first element becomes the last).

Original array:
``` python
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
```
``` python
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]
```

In [ ]:
a = np.arange(12, 38)

In [ ]:
a[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [ ]:
np.flip(a)

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

6.  Write a NumPy program to convert an array to a floating type.

Sample output:

Original array
``` pyhton
[1, 2, 3, 4]
```

Array converted to a float type:
``` python
[ 1. 2. 3. 4.]
```

In [ ]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

7. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [ ]:
x = np.ones((8, 8))
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x[1:-1, 1:-1] = 0

In [ ]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

8. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [ ]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.pad(x, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# Pandas Foundations

In [ ]:
import pandas as pd
import numpy as np

## Dissecting the anatomy of a DataFrame

### Change options to get specific output for book

In [ ]:
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)

In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie.tail()

color     director_name  num_critic_for_reviews  duration  ...  \
4911  Color       Scott Smith                     1.0      87.0  ...   
4912  Color               NaN                    43.0      43.0  ...   
4913  Color  Benjamin Roberds                    13.0      76.0  ...   
4914  Color       Daniel Hsia                    14.0     100.0  ...   
4915  Color          Jon Gunn                    43.0      90.0  ...   

      actor_2_facebook_likes  imdb_score aspect_ratio  movie_facebook_likes  
4911                   470.0         7.7          NaN                    84  
4912                   593.0         7.5        16.00                 32000  
4913                     0.0         6.3          NaN                    16  
4914                   719.0         6.3         2.35                   660  
4915                    23.0         6.6         1.85                   456  

[5 rows x 28 columns]

|index|color|director\_name|num\_critic\_for\_reviews|duration|director\_facebook\_likes|actor\_3\_facebook\_likes|actor\_2\_name|actor\_1\_facebook\_likes|gross|genres|actor\_1\_name|movie\_title|num\_voted\_users|cast\_total\_facebook\_likes|actor\_3\_name|facenumber\_in\_poster|plot\_keywords|movie\_imdb\_link|num\_user\_for\_reviews|language|country|content\_rating|budget|title\_year|actor\_2\_facebook\_likes|imdb\_score|aspect\_ratio|movie\_facebook\_likes|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|0|Color|James Cameron|723\.0|178\.0|0\.0|855\.0|Joel David Moore|1000\.0|760505847\.0|Action&#124;Adventure&#124;Fantasy&#124;Sci-Fi|CCH Pounder|Avatar|886204|4834|Wes Studi|0\.0|avatar&#124;future&#124;marine&#124;native&#124;paraplegic|http://www\.imdb\.com/title/tt0499549/?ref\_=fn\_tt\_tt\_1|3054\.0|English|USA|PG-13|237000000\.0|2009\.0|936\.0|7\.9|1\.78|33000|
|1|Color|Gore Verbinski|302\.0|169\.0|563\.0|1000\.0|Orlando Bloom|40000\.0|309404152\.0|Action&#124;Adventure&#124;Fantasy|Johnny Depp|Pirates of the Caribbean: At World's End|471220|48350|Jack Davenport|0\.0|goddess&#124;marriage ceremony&#124;marriage proposal&#124;pirate&#124;singapore|http://www\.imdb\.com/title/tt0449088/?ref\_=fn\_tt\_tt\_1|1238\.0|English|USA|PG-13|300000000\.0|2007\.0|5000\.0|7\.1|2\.35|0|
|2|Color|Sam Mendes|602\.0|148\.0|0\.0|161\.0|Rory Kinnear|11000\.0|200074175\.0|Action&#124;Adventure&#124;Thriller|Christoph Waltz|Spectre|275868|11700|Stephanie Sigman|1\.0|bomb&#124;espionage&#124;sequel&#124;spy&#124;terrorist|http://www\.imdb\.com/title/tt2379713/?ref\_=fn\_tt\_tt\_1|994\.0|English|UK|PG-13|245000000\.0|2015\.0|393\.0|6\.8|2\.35|85000|
|3|Color|Christopher Nolan|813\.0|164\.0|22000\.0|23000\.0|Christian Bale|27000\.0|448130642\.0|Action&#124;Thriller|Tom Hardy|The Dark Knight Rises|1144337|106759|Joseph Gordon-Levitt|0\.0|deception&#124;imprisonment&#124;lawlessness&#124;police officer&#124;terrorist plot|http://www\.imdb\.com/title/tt1345836/?ref\_=fn\_tt\_tt\_1|2701\.0|English|USA|PG-13|250000000\.0|2012\.0|23000\.0|8\.5|2\.35|164000|
|4|NaN|Doug Walker|NaN|NaN|131\.0|NaN|Rob Walker|131\.0|NaN|Documentary|Doug Walker|Star Wars: Episode VII - The Force Awakens|8|143|NaN|0\.0|NaN|http://www\.imdb\.com/title/tt5289954/?ref\_=fn\_tt\_tt\_1|NaN|NaN|NaN|NaN|NaN|NaN|12\.0|7\.1|NaN|0|

In [ ]:
from google.colab import data_table
data_table.DataTable.max_columns = 30
data_table.enable_dataframe_formatter()
movie.head()

color      director_name  num_critic_for_reviews  duration  ...  \
0  Color      James Cameron                   723.0     178.0  ...   
1  Color     Gore Verbinski                   302.0     169.0  ...   
2  Color         Sam Mendes                   602.0     148.0  ...   
3  Color  Christopher Nolan                   813.0     164.0  ...   
4    NaN        Doug Walker                     NaN       NaN  ...   

   actor_2_facebook_likes  imdb_score aspect_ratio  movie_facebook_likes  
0                   936.0         7.9         1.78                 33000  
1                  5000.0         7.1         2.35                     0  
2                   393.0         6.8         2.35                 85000  
3                 23000.0         8.5         2.35                164000  
4                    12.0         7.1          NaN                     0  

[5 rows x 28 columns]

## Accessing the main DataFrame components

In [ ]:
movie.head()

color      director_name  num_critic_for_reviews  duration  ...  \
0  Color      James Cameron                   723.0     178.0  ...   
1  Color     Gore Verbinski                   302.0     169.0  ...   
2  Color         Sam Mendes                   602.0     148.0  ...   
3  Color  Christopher Nolan                   813.0     164.0  ...   
4    NaN        Doug Walker                     NaN       NaN  ...   

   actor_2_facebook_likes  imdb_score aspect_ratio  movie_facebook_likes  
0                   936.0         7.9         1.78                 33000  
1                  5000.0         7.1         2.35                     0  
2                   393.0         6.8         2.35                 85000  
3                 23000.0         8.5         2.35                164000  
4                    12.0         7.1          NaN                     0  

[5 rows x 28 columns]

In [ ]:
columns = movie.columns
index = movie.index
data = movie.values

In [ ]:
columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [ ]:
index

RangeIndex(start=0, stop=4916, step=1)

In [ ]:
data

array([['Color', 'James Cameron', 723.0, ..., 7.9, 1.78, 33000],
       ['Color', 'Gore Verbinski', 302.0, ..., 7.1, 2.35, 0],
       ['Color', 'Sam Mendes', 602.0, ..., 6.8, 2.35, 85000],
       ...,
       ['Color', 'Benjamin Roberds', 13.0, ..., 6.3, nan, 16],
       ['Color', 'Daniel Hsia', 14.0, ..., 6.3, 2.35, 660],
       ['Color', 'Jon Gunn', 43.0, ..., 6.6, 1.85, 456]], dtype=object)

In [ ]:
type(index)

pandas.core.indexes.range.RangeIndex

In [ ]:
type(columns)

In [ ]:
type(data)

numpy.ndarray

### There's more

In [ ]:
type(index.values)

numpy.ndarray

In [ ]:
columns.values

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

## Understanding data types

In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie.dtypes

color                       object
director_name               object
num_critic_for_reviews     float64
duration                   float64
director_facebook_likes    float64
                            ...   
title_year                 float64
actor_2_facebook_likes     float64
imdb_score                 float64
aspect_ratio               float64
movie_facebook_likes         int64
Length: 28, dtype: object

In [ ]:
movie.dtypes.value_counts()

float64    13
object     12
int64       3
Name: count, dtype: int64

## Selecting a single column of data as a Series

In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
movie['director_name']

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [ ]:
movie.director_name

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [ ]:
type(movie)

pandas.core.frame.DataFrame

In [ ]:
type(movie['director_name'])

pandas.core.series.Series

### There's more

In [ ]:
director = movie['director_name']
director.name

'director_name'

In [ ]:
type(director.to_frame())

pandas.core.frame.DataFrame

## Calling Series methods

### Getting ready...

In [ ]:
s_attr_methods = set(dir(pd.Series))
len(s_attr_methods)

419

In [ ]:
df_attr_methods = set(dir(pd.DataFrame))
len(df_attr_methods)

438

In [ ]:
len(s_attr_methods & df_attr_methods)

362

### How to do it...

In [ ]:
movie

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
movie = pd.read_csv('data/movie.csv')
director = movie['director_name']
actor_1_fb_likes = movie['actor_1_facebook_likes']

In [ ]:
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [ ]:
actor_1_fb_likes.head()

0     1000.0
1    40000.0
2    11000.0
3    27000.0
4      131.0
Name: actor_1_facebook_likes, dtype: float64

In [ ]:
director.value_counts()

director_name
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
John Putch           1
Luca Guadagnino      1
Sam Fell             1
Dan Fogelman         1
Daniel Hsia          1
Name: count, Length: 2397, dtype: int64

In [ ]:
actor_1_fb_likes.value_counts()

actor_1_facebook_likes
1000.0     436
11000.0    206
2000.0     189
3000.0     150
12000.0    131
          ... 
703.0        1
208.0        1
79.0         1
269.0        1
291.0        1
Name: count, Length: 877, dtype: int64

In [ ]:
director.size

4916

In [ ]:
movie.shape

(4916, 28)

In [ ]:
director.shape

(4916,)

In [ ]:
len(director)

4916

In [ ]:
director.count()

4814

In [ ]:
actor_1_fb_likes.count()

4909

In [ ]:
actor_1_fb_likes.quantile()

240.0

In [ ]:
10 / 3

3.3333333333333335

In [ ]:
actor_1_fb_likes.min(), actor_1_fb_likes.max(), \
actor_1_fb_likes.mean(), actor_1_fb_likes.median(), \
actor_1_fb_likes.std(), actor_1_fb_likes.sum()

(0.0, 640000.0, 6494.488490527602, 982.0, 15106.986883848309, 31881444.0)

In [ ]:
actor_1_fb_likes.shape

(4916,)

In [ ]:
actor_1_fb_likes.describe()

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

In [ ]:
director.describe()

count                 4814
unique                2397
top       Steven Spielberg
freq                    26
Name: director_name, dtype: object

In [ ]:
actor_1_fb_likes.quantile(.2)

510.0

In [ ]:
actor_1_fb_likes.quantile([.1, .2, .3, .4, .5, .6, .7, .8, .9])

0.1      240.0
0.2      510.0
0.3      694.0
0.4      854.0
0.5      982.0
0.6     1000.0
0.7     8000.0
0.8    13000.0
0.9    18000.0
Name: actor_1_facebook_likes, dtype: float64

In [ ]:
director.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [ ]:
actor_1_fb_likes.count()

4909

In [ ]:
actor_1_fb_likes_filled = actor_1_fb_likes.fillna(0)
actor_1_fb_likes_filled.count()

4916

In [ ]:
actor_1_fb_likes_filled.shape

(4916,)

In [ ]:
actor_1_fb_likes_dropped = actor_1_fb_likes.dropna()
actor_1_fb_likes_dropped.size

4909

### There's more...

In [ ]:
director.value_counts(normalize=True)

director_name
Steven Spielberg    0.005401
Woody Allen         0.004570
Martin Scorsese     0.004155
Clint Eastwood      0.004155
Ridley Scott        0.003324
                      ...   
John Putch          0.000208
Luca Guadagnino     0.000208
Sam Fell            0.000208
Dan Fogelman        0.000208
Daniel Hsia         0.000208
Name: proportion, Length: 2397, dtype: float64

In [ ]:
director

In [ ]:
director.hasnans

True

In [ ]:
%%shell

head -n 5 ./data/movie.csv

color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pirate|singapore,http://www.imdb.com

In [ ]:
pd.read_excel('./data')

In [ ]:
pd.DataFrame({'a': [1, 2, 3], 'b': [5, 6, 7]})

a  b
0  1  5
1  2  6
2  3  7

In [ ]:
director.notnull()

0        True
1        True
2        True
3        True
4        True
        ...  
4911     True
4912    False
4913     True
4914     True
4915     True
Name: director_name, Length: 4916, dtype: bool

## Digression on floating point numbers

In [ ]:
print(0.1 + 0.2)

0.30000000000000004


In [ ]:
print(0.1 + 0.2 == 0.3)

False


In [ ]:
from math import isclose

print(isclose(0.1 + 0.2, 0.3))

In [ ]:
total = 0.0
for _ in range(1000000):
    total += 0.000001

In [ ]:
print(total == 1)

False


In [ ]:
import math

numbers = [0.000001] * 1000000
total = math.fsum(numbers)
print(total)

1.0


In [ ]:
small_number = 1e-323
small_number


1e-323

In [ ]:
print(small_number / 10)

0.0


In [ ]:
a = 1.0000001
b = 1.0000000

In [ ]:
print(a - b)

1.0000000005838672e-07


In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie

Output hidden; open in https://colab.research.google.com to view.

## Working with operators on a Series

### Getting ready...

In [ ]:
movie

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
movie = pd.read_csv('data/movie.csv')
imdb_score = movie['imdb_score']
imdb_score

0       7.9
1       7.1
2       6.8
3       8.5
4       7.1
       ... 
4911    7.7
4912    7.5
4913    6.3
4914    6.3
4915    6.6
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score + 1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ... 
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score * 2.5

0       19.75
1       17.75
2       17.00
3       21.25
4       17.75
        ...  
4911    19.25
4912    18.75
4913    15.75
4914    15.75
4915    16.50
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score // 7

0       1.0
1       1.0
2       0.0
3       1.0
4       1.0
       ... 
4911    1.0
4912    1.0
4913    0.0
4914    0.0
4915    0.0
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score > 7

0        True
1        True
2       False
3        True
4        True
        ...  
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

In [ ]:
director = movie['director_name']

In [ ]:
director

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [ ]:
director == 'James Cameron'

0        True
1       False
2       False
3       False
4       False
        ...  
4911    False
4912    False
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

### There's more...

In [ ]:
imdb_score.add(1)              # imdb_score + 1

0       8.9
1       8.1
2       7.8
3       9.5
4       8.1
       ... 
4911    8.7
4912    8.5
4913    7.3
4914    7.3
4915    7.6
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score.mul(2.5)            # imdb_score * 2.5

0       19.75
1       17.75
2       17.00
3       21.25
4       17.75
        ...  
4911    19.25
4912    18.75
4913    15.75
4914    15.75
4915    16.50
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score.floordiv(7)         # imdb_score // 7

0       1.0
1       1.0
2       0.0
3       1.0
4       1.0
       ... 
4911    1.0
4912    1.0
4913    0.0
4914    0.0
4915    0.0
Name: imdb_score, Length: 4916, dtype: float64

In [ ]:
imdb_score.gt(7)               # imdb_score > 7

0        True
1        True
2       False
3        True
4        True
        ...  
4911     True
4912     True
4913    False
4914    False
4915    False
Name: imdb_score, Length: 4916, dtype: bool

In [ ]:
director.eq('James Cameron')   # director == 'James Cameron'

0        True
1       False
2       False
3       False
4       False
        ...  
4911    False
4912    False
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [ ]:
imdb_score.astype(int).mod(5)

0       2
1       2
2       1
3       3
4       2
       ..
4911    2
4912    2
4913    1
4914    1
4915    1
Name: imdb_score, Length: 4916, dtype: int64

## Chaining Series methods together

In [ ]:
movie = pd.read_csv('data/movie.csv')
actor_1_fb_likes = movie['actor_1_facebook_likes']
director = movie['director_name']

In [ ]:
director.value_counts().value_counts()

count
1     1523
2      363
3      173
4      124
5       74
      ... 
15       2
16       2
20       2
22       1
26       1
Name: count, Length: 19, dtype: int64

In [ ]:
director.value_counts().head(3)

director_name
Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Name: count, dtype: int64

In [ ]:
actor_1_fb_likes.isnull().value_counts()

actor_1_facebook_likes
False    4909
True        7
Name: count, dtype: int64

In [ ]:
actor_1_fb_likes.dtype

dtype('float64')

In [ ]:
actor_1_fb_likes.fillna(0)\
                .astype(int)\
                .head()

### There's more...

In [ ]:
actor_1_fb_likes.isnull().mean()

0.0014239218877135883

In [ ]:
(actor_1_fb_likes.fillna(0)
                 .astype(int)
                 .head())

0     1000
1    40000
2    11000
3    27000
4      131
Name: actor_1_facebook_likes, dtype: int64

## Making the index meaningful

In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
movie.shape

(4916, 28)

In [ ]:
movie2 = movie.set_index('movie_title')
movie2

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
pd.read_csv('data/movie.csv').set_index('movie_title')

In [ ]:
pd.read_csv('data/movie.csv', index_col='movie_title')

Output hidden; open in https://colab.research.google.com to view.

## There's more...

In [ ]:
movie2.reset_index(drop=True)

Output hidden; open in https://colab.research.google.com to view.

# Renaming row and column names

In [ ]:
movie = pd.read_csv('data/movie.csv', index_col='movie_title')

In [ ]:
idx_rename = {'Avatar':'Ratava', 'Spectre': 'Ertceps'}
col_rename = {'director_name':'Director Name',
              'num_critic_for_reviews': 'Critical Reviews'}

In [ ]:
movie.rename(index=idx_rename,
             columns=col_rename,
             ).head()

color      Director Name  \
movie_title                                                            
Ratava                                      Color      James Cameron   
Pirates of the Caribbean: At World's End    Color     Gore Verbinski   
Ertceps                                     Color         Sam Mendes   
The Dark Knight Rises                       Color  Christopher Nolan   
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker   

                                            Critical Reviews  duration  ...  \
movie_title                                                             ...   
Ratava                                                 723.0     178.0  ...   
Pirates of the Caribbean: At World's End               302.0     169.0  ...   
Ertceps                                                602.0     148.0  ...   
The Dark Knight Rises                                  813.0     164.0  ...   
Star Wars: Episode VII - The Force Awakens               NaN       NaN  ...   

                                            actor_2_facebook_likes  \
movie_title                                                          
Ratava                                                       936.0   
Pirates of the Caribbean: At World's End                    5000.0   
Ertceps                                                      393.0   
The Dark Knight Rises                                      23000.0   
Star Wars: Episode VII - The Force Awakens                    12.0   

                                            imdb_score aspect_ratio  \
movie_title                                                           
Ratava                                             7.9         1.78   
Pirates of the Caribbean: At World's End           7.1         2.35   
Ertceps                                            6.8         2.35   
The Dark Knight Rises                              8.5         2.35   
Star Wars: Episode VII - The Force Awakens         7.1          NaN   

                                            movie_facebook_likes  
movie_title                                                       
Ratava                                                     33000  
Pirates of the Caribbean: At World's End                       0  
Ertceps                                                    85000  
The Dark Knight Rises                                     164000  
Star Wars: Episode VII - The Force Awakens                     0  

[5 rows x 27 columns]

## There's more

In [ ]:
movie = pd.read_csv('data/movie.csv', index_col='movie_title')
index = movie.index
columns = movie.columns

In [ ]:
index.tolist()

In [ ]:
columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'num_voted_users', 'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [ ]:
index_list = index.tolist()
column_list = columns.tolist()

In [ ]:
index_list

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'Star Wars: Episode VII - The Force Awakens',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz the Gre

In [ ]:




index_list[0] = 'Ratava'
index_list[2] = 'Ertceps'
column_list[1] = 'Director Name'
column_list[2] = 'Critical Reviews'

In [ ]:
movie.index = index_list

In [ ]:
print(index_list[:5])

In [ ]:
print(column_list)

In [ ]:
movie.index = index_list
movie.columns = column_list

In [ ]:
movie.head()

color      Director Name  \
Ratava                                      Color      James Cameron   
Pirates of the Caribbean: At World's End    Color     Gore Verbinski   
Ertceps                                     Color         Sam Mendes   
The Dark Knight Rises                       Color  Christopher Nolan   
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker   

                                            Critical Reviews  duration  ...  \
Ratava                                                 723.0     178.0  ...   
Pirates of the Caribbean: At World's End               302.0     169.0  ...   
Ertceps                                                602.0     148.0  ...   
The Dark Knight Rises                                  813.0     164.0  ...   
Star Wars: Episode VII - The Force Awakens               NaN       NaN  ...   

                                            actor_2_facebook_likes  \
Ratava                                                       936.0   
Pirates of the Caribbean: At World's End                    5000.0   
Ertceps                                                      393.0   
The Dark Knight Rises                                      23000.0   
Star Wars: Episode VII - The Force Awakens                    12.0   

                                            imdb_score aspect_ratio  \
Ratava                                             7.9         1.78   
Pirates of the Caribbean: At World's End           7.1         2.35   
Ertceps                                            6.8         2.35   
The Dark Knight Rises                              8.5         2.35   
Star Wars: Episode VII - The Force Awakens         7.1          NaN   

                                            movie_facebook_likes  
Ratava                                                     33000  
Pirates of the Caribbean: At World's End                       0  
Ertceps                                                    85000  
The Dark Knight Rises                                     164000  
Star Wars: Episode VII - The Force Awakens                     0  

[5 rows x 27 columns]

# Creating and deleting columns

In [ ]:
movie = pd.read_csv('data/movie.csv')

In [ ]:
movie['has_seen'] = 0

In [ ]:
movie.has_seen

0       0
1       0
2       0
3       0
4       0
       ..
4911    0
4912    0
4913    0
4914    0
4915    0
Name: has_seen, Length: 4916, dtype: int64

In [ ]:
movie['actor_director_facebook_likes'] = (movie['actor_1_facebook_likes'] +
                                          movie['actor_2_facebook_likes'] +
                                          movie['actor_3_facebook_likes'] +
                                          movie['director_facebook_likes'])

In [ ]:
movie['actor_director_facebook_likes'].isnull().sum()

122

In [ ]:
movie['actor_director_facebook_likes'].fillna(0)

0        2791.0
1       46563.0
2       11554.0
3       95000.0
4           0.0
         ...   
4911     1427.0
4912        0.0
4913        0.0
4914     2154.0
4915      141.0
Name: actor_director_facebook_likes, Length: 4916, dtype: float64

In [ ]:
movie['actor_director_facebook_likes'] = movie['actor_director_facebook_likes'].fillna(0)

In [ ]:
movie['is_cast_likes_more'] = (movie['cast_total_facebook_likes'] >=
                                  movie['actor_director_facebook_likes'])

In [ ]:
movie['is_cast_likes_more'].any()

True

In [ ]:
movie = movie.drop('actor_director_facebook_likes', axis='columns')

In [ ]:
movie['actor_total_facebook_likes'] = (movie['actor_1_facebook_likes'] +
                                       movie['actor_2_facebook_likes'] +
                                       movie['actor_3_facebook_likes'])

movie['actor_total_facebook_likes'] = movie['actor_total_facebook_likes'].fillna(0)

In [ ]:
movie['is_cast_likes_more'] = movie['cast_total_facebook_likes'] >= \
                                  movie['actor_total_facebook_likes']

movie['is_cast_likes_more'].all()

True

In [ ]:
movie['pct_actor_cast_like'] = (movie['actor_total_facebook_likes'] /
                                movie['cast_total_facebook_likes'])

In [ ]:
movie['pct_actor_cast_like'].min(), movie['pct_actor_cast_like'].max()

(0.0, 1.0)

In [ ]:
movie.set_index('movie_title')['pct_actor_cast_like'].head()

movie_title
Avatar                                        0.577369
Pirates of the Caribbean: At World's End      0.951396
Spectre                                       0.987521
The Dark Knight Rises                         0.683783
Star Wars: Episode VII - The Force Awakens    0.000000
Name: pct_actor_cast_like, dtype: float64

### There's more...

In [ ]:
profit_index = movie.columns.get_loc('gross') + 1
profit_index

In [ ]:
movie.insert(loc=profit_index,
                 column='profit',
                 value=movie['gross'] - movie['budget'])

In [ ]:
movie.head()

## Selecting Series data

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
city = college['CITY']
city.head()

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [ ]:
city.iloc[3]

'Huntsville'

In [ ]:
city.iloc[[10,20,30]]

INSTNM
Birmingham Southern College                            Birmingham
George C Wallace State Community College-Hanceville    Hanceville
Judson College                                             Marion
Name: CITY, dtype: object

In [ ]:
city.iloc[4:50:10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

In [ ]:
city

INSTNM
Alabama A & M University                                            Normal
University of Alabama at Birmingham                             Birmingham
Amridge University                                              Montgomery
University of Alabama in Huntsville                             Huntsville
Alabama State University                                        Montgomery
                                                                ...       
SAE Institute of Technology  San Francisco                      Emeryville
Rasmussen College - Overland Park                            Overland Park
National Personal Training Institute of Cleveland         Highland Heights
Bay Area Medical Academy - San Jose Satellite Location            San Jose
Excel Learning Center-San Antonio South                        San Antonio
Name: CITY, Length: 7535, dtype: object

In [ ]:
city.loc['Heritage Christian University']

'Florence'

In [ ]:
np.random.choice(city.index, 4)

array(['Baptist Health College-Little Rock',
       'Widener University-Delaware Law School',
       'The Art Institute of Cincinnati-AIC College of Design',
       'South University-Accelerated Graduate Programs'], dtype=object)

In [ ]:

labels = list(np.random.choice(city.index, 4))
labels

['University of South Carolina-Union',
 'Strayer University-White Marsh Campus',
 'Indiana University-East',
 'Franklin W Olin College of Engineering']

In [ ]:
city.loc[labels]

INSTNM
University of South Carolina-Union            Union
Strayer University-White Marsh Campus     Baltimore
Indiana University-East                    Richmond
Franklin W Olin College of Engineering      Needham
Name: CITY, dtype: object

In [ ]:
city.loc['Alabama State University':'Reid State Technical College':10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

In [ ]:
city['Alabama State University':'Reid State Technical College':10]

INSTNM
Alabama State University              Montgomery
Enterprise State Community College    Enterprise
Heritage Christian University           Florence
Marion Military Institute                 Marion
Reid State Technical College           Evergreen
Name: CITY, dtype: object

## There's more...

In [ ]:
city.iloc[[3]]

INSTNM
University of Alabama in Huntsville    Huntsville
Name: CITY, dtype: object

In [ ]:
city.loc['Reid State Technical College':'Alabama State University':10]

Series([], Name: CITY, dtype: object)

In [ ]:
city.loc['Reid State Technical College':'Alabama State University':-10]

INSTNM
Reid State Technical College           Evergreen
Marion Military Institute                 Marion
Heritage Christian University           Florence
Enterprise State Community College    Enterprise
Alabama State University              Montgomery
Name: CITY, dtype: object

# Selecting DataFrame rows

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college.head()

CITY STABBR  HBCU  MENONLY  ...  \
INSTNM                                                                 ...   
Alabama A & M University                 Normal     AL   1.0      0.0  ...   
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0  ...   
Amridge University                   Montgomery     AL   0.0      0.0  ...   
University of Alabama in Huntsville  Huntsville     AL   0.0      0.0  ...   
Alabama State University             Montgomery     AL   1.0      0.0  ...   

                                     PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  \
INSTNM                                                                    
Alabama A & M University               0.8284   0.1049            30300   
University of Alabama at Birmingham    0.5214   0.2422            39700   
Amridge University                     0.7795   0.8540            40100   
University of Alabama in Huntsville    0.4596   0.2640            45500   
Alabama State University               0.7554   0.1270            26600   

                                     GRAD_DEBT_MDN_SUPP  
INSTNM                                                   
Alabama A & M University                          33888  
University of Alabama at Birmingham             21941.5  
Amridge University                                23370  
University of Alabama in Huntsville               24097  
Alabama State University                        33118.5  

[5 rows x 26 columns]

In [ ]:
pd.options.display.max_rows = 6

In [ ]:
college.iloc[60]

CITY                  Anchorage
STABBR                       AK
HBCU                        0.0
MENONLY                     0.0
WOMENONLY                   0.0
                        ...    
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, Length: 26, dtype: object

In [ ]:
college.loc['University of Alaska Anchorage']

CITY                  Anchorage
STABBR                       AK
HBCU                        0.0
MENONLY                     0.0
WOMENONLY                   0.0
                        ...    
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, Length: 26, dtype: object

In [ ]:
college.iloc[[60, 99, 3]]

CITY STABBR  HBCU  MENONLY  ...  \
INSTNM                                                                  ...   
University of Alaska Anchorage         Anchorage     AK   0.0      0.0  ...   
International Academy of Hair Design       Tempe     AZ   0.0      0.0  ...   
University of Alabama in Huntsville   Huntsville     AL   0.0      0.0  ...   

                                      PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  \
INSTNM                                                                     
University of Alaska Anchorage          0.2647   0.4386            42500   
International Academy of Hair Design    0.7346   0.3905            22200   
University of Alabama in Huntsville     0.4596   0.2640            45500   

                                      GRAD_DEBT_MDN_SUPP  
INSTNM                                                    
University of Alaska Anchorage                   19449.5  
International Academy of Hair Design               10556  
University of Alabama in Huntsville                24097  

[3 rows x 26 columns]

In [ ]:
labels = ['University of Alaska Anchorage',
          'International Academy of Hair Design',
          'University of Alabama in Huntsville']
college.loc[labels]

CITY STABBR  HBCU  MENONLY  ...  \
INSTNM                                                                  ...   
University of Alaska Anchorage         Anchorage     AK   0.0      0.0  ...   
International Academy of Hair Design       Tempe     AZ   0.0      0.0  ...   
University of Alabama in Huntsville   Huntsville     AL   0.0      0.0  ...   

                                      PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  \
INSTNM                                                                     
University of Alaska Anchorage          0.2647   0.4386            42500   
International Academy of Hair Design    0.7346   0.3905            22200   
University of Alabama in Huntsville     0.4596   0.2640            45500   

                                      GRAD_DEBT_MDN_SUPP  
INSTNM                                                    
University of Alaska Anchorage                   19449.5  
International Academy of Hair Design               10556  
University of Alabama in Huntsville                24097  

[3 rows x 26 columns]

In [ ]:
college.iloc[99:102]

CITY STABBR  HBCU  MENONLY  ...  \
INSTNM                                                               ...   
International Academy of Hair Design    Tempe     AZ   0.0      0.0  ...   
GateWay Community College             Phoenix     AZ   0.0      0.0  ...   
Mesa Community College                   Mesa     AZ   0.0      0.0  ...   

                                      PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  \
INSTNM                                                                     
International Academy of Hair Design    0.7346   0.3905            22200   
GateWay Community College               0.2189   0.5832            29800   
Mesa Community College                  0.2207   0.4010            35200   

                                      GRAD_DEBT_MDN_SUPP  
INSTNM                                                    
International Academy of Hair Design               10556  
GateWay Community College                           7283  
Mesa Community College                              8000  

[3 rows x 26 columns]

In [ ]:
start = 'International Academy of Hair Design'
stop = 'Mesa Community College'
college.loc[start:stop]

CITY STABBR  HBCU  MENONLY  ...  \
INSTNM                                                               ...   
International Academy of Hair Design    Tempe     AZ   0.0      0.0  ...   
GateWay Community College             Phoenix     AZ   0.0      0.0  ...   
Mesa Community College                   Mesa     AZ   0.0      0.0  ...   

                                      PCTFLOAN  UG25ABV  MD_EARN_WNE_P10  \
INSTNM                                                                     
International Academy of Hair Design    0.7346   0.3905            22200   
GateWay Community College               0.2189   0.5832            29800   
Mesa Community College                  0.2207   0.4010            35200   

                                      GRAD_DEBT_MDN_SUPP  
INSTNM                                                    
International Academy of Hair Design               10556  
GateWay Community College                           7283  
Mesa Community College                              8000  

[3 rows x 26 columns]

In [ ]:
college.iloc[[60, 99, 3]].index.tolist()

['University of Alaska Anchorage',
 'International Academy of Hair Design',
 'University of Alabama in Huntsville']

# Selecting DataFrame rows and columns simultaneously

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college.iloc[:3, :4]

CITY STABBR  HBCU  MENONLY
INSTNM                                                               
Alabama A & M University                 Normal     AL   1.0      0.0
University of Alabama at Birmingham  Birmingham     AL   0.0      0.0
Amridge University                   Montgomery     AL   0.0      0.0

In [ ]:
college.loc[:'Amridge University', :'MENONLY']

In [ ]:
college.iloc[:, [4,6]].head()

WOMENONLY  SATVRMID
INSTNM                                                  
Alabama A & M University                   0.0     424.0
University of Alabama at Birmingham        0.0     570.0
Amridge University                         0.0       NaN
University of Alabama in Huntsville        0.0     595.0
Alabama State University                   0.0     425.0

In [ ]:
college.loc[:, ['WOMENONLY', 'SATVRMID']]

WOMENONLY  SATVRMID
INSTNM                                                                 
Alabama A & M University                                  0.0     424.0
University of Alabama at Birmingham                       0.0     570.0
Amridge University                                        0.0       NaN
University of Alabama in Huntsville                       0.0     595.0
Alabama State University                                  0.0     425.0
...                                                       ...       ...
SAE Institute of Technology  San Francisco                NaN       NaN
Rasmussen College - Overland Park                         NaN       NaN
National Personal Training Institute of Cleveland         NaN       NaN
Bay Area Medical Academy - San Jose Satellite L...        NaN       NaN
Excel Learning Center-San Antonio South                   NaN       NaN

[7535 rows x 2 columns]

In [ ]:
college.iloc[[100, 200], [7, 15]]

SATMTMID  UGDS_NHPI
INSTNM                                                    
GateWay Community College                   NaN     0.0029
American Baptist Seminary of the West       NaN        NaN

In [ ]:
rows = ['GateWay Community College', 'American Baptist Seminary of the West']
columns = ['SATMTMID', 'UGDS_NHPI']
college.loc[rows, columns]

In [ ]:
college.iloc[5, -4]

In [ ]:
college.loc['The University of Alabama', 'PCTFLOAN']

In [ ]:
college.iloc[90:80:-2, 5]

In [ ]:
start = 'Empire Beauty School-Flagstaff'
stop = 'Arizona State University-Tempe'
college.loc[start:stop:-2, 'RELAFFIL']

# Selecting data with both integers and labels

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [ ]:
college.columns.get_loc('UGDS_WHITE')

10

In [ ]:
col_start = college.columns.get_loc('UGDS_WHITE')
col_end = college.columns.get_loc('UGDS_UNKN') + 1
col_start, col_end

(10, 19)

In [ ]:
college.iloc[:5, col_start:col_end]

UGDS_WHITE  UGDS_BLACK  UGDS_HISP  \
INSTNM                                                                   
Alabama A & M University                 0.0333      0.9353     0.0055   
University of Alabama at Birmingham      0.5922      0.2600     0.0283   
Amridge University                       0.2990      0.4192     0.0069   
University of Alabama in Huntsville      0.6988      0.1255     0.0382   
Alabama State University                 0.0158      0.9208     0.0121   

                                     UGDS_ASIAN  ...  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                           ...                         
Alabama A & M University                 0.0019  ...     0.0019     0.0000   
University of Alabama at Birmingham      0.0518  ...     0.0007     0.0368   
Amridge University                       0.0034  ...     0.0000     0.0000   
University of Alabama in Huntsville      0.0376  ...     0.0002     0.0172   
Alabama State University                 0.0019  ...     0.0006     0.0098   

                                     UGDS_NRA  UGDS_UNKN  
INSTNM                                                    
Alabama A & M University               0.0059     0.0138  
University of Alabama at Birmingham    0.0179     0.0100  
Amridge University                     0.0000     0.2715  
University of Alabama in Huntsville    0.0332     0.0350  
Alabama State University               0.0243     0.0137  

[5 rows x 9 columns]

In [ ]:
row_start = college.index[10]
row_end = college.index[15]
print(row_start)
college.loc[row_start:row_end, 'UGDS_WHITE':'UGDS_UNKN']

Birmingham Southern College


UGDS_WHITE  UGDS_BLACK  UGDS_HISP  \
INSTNM                                                                        
Birmingham Southern College                   0.7983      0.1102     0.0195   
Chattahoochee Valley Community College        0.4661      0.4372     0.0492   
Concordia College Alabama                     0.0280      0.8758     0.0373   
South University-Montgomery                   0.3046      0.6054     0.0153   
Enterprise State Community College            0.6408      0.2435     0.0509   
James H Faulkner State Community College      0.6979      0.2259     0.0320   

                                          UGDS_ASIAN  ...  UGDS_NHPI  \
INSTNM                                                ...              
Birmingham Southern College                   0.0517  ...     0.0000   
Chattahoochee Valley Community College        0.0127  ...     0.0035   
Concordia College Alabama                     0.0093  ...     0.0000   
South University-Montgomery                   0.0153  ...     0.0096   
Enterprise State Community College            0.0202  ...     0.0029   
James H Faulkner State Community College      0.0084  ...     0.0014   

                                          UGDS_2MOR  UGDS_NRA  UGDS_UNKN  
INSTNM                                                                    
Birmingham Southern College                  0.0051    0.0000     0.0051  
Chattahoochee Valley Community College       0.0151    0.0000     0.0139  
Concordia College Alabama                    0.0031    0.0466     0.0000  
South University-Montgomery                  0.0000    0.0019     0.0326  
Enterprise State Community College           0.0254    0.0012     0.0069  
James H Faulkner State Community College     0.0152    0.0007     0.0009  

[6 rows x 9 columns]

# Speeding up scalar selection

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
cn = 'Texas A & M University-College Station'
college.loc[cn, 'UGDS_WHITE']

In [ ]:
college.at[cn, 'UGDS_WHITE']

In [ ]:
%timeit college.loc[cn, 'UGDS_WHITE']

In [ ]:
%timeit college.at[cn, 'UGDS_WHITE']

In [ ]:
row_num = college.index.get_loc(cn)
col_num = college.columns.get_loc('UGDS_WHITE')

In [ ]:
row_num, col_num

In [ ]:
%timeit college.iloc[row_num, col_num]

In [ ]:
%timeit college.iat[row_num, col_num]

In [ ]:
%timeit college.iloc[5, col_num]

In [ ]:
%timeit college.iat[5, col_num]

In [ ]:
state = college['STABBR']

In [ ]:
state.iat[1000]

In [ ]:
state.at['Stanford University']

# Slicing Lexicographically

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college.loc['Sp':'Su']

KeyError: 'Sp'

In [ ]:
college = college.sort_index()

In [ ]:
college.head()

CITY STABBR  HBCU  \
INSTNM                                                                         
A & W Healthcare Educators                          New Orleans     LA   0.0   
A T Still University of Health Sciences              Kirksville     MO   0.0   
ABC Beauty Academy                                      Garland     TX   0.0   
ABC Beauty College Inc                              Arkadelphia     AR   0.0   
AI Miami International University of Art and De...        Miami     FL   0.0   

                                                    MENONLY  ...  PCTFLOAN  \
INSTNM                                                       ...             
A & W Healthcare Educators                              0.0  ...    0.8596   
A T Still University of Health Sciences                 0.0  ...       NaN   
ABC Beauty Academy                                      0.0  ...    0.0000   
ABC Beauty College Inc                                  0.0  ...    1.0000   
AI Miami International University of Art and De...      0.0  ...    0.6966   

                                                    UG25ABV  \
INSTNM                                                        
A & W Healthcare Educators                           0.6667   
A T Still University of Health Sciences                 NaN   
ABC Beauty Academy                                   0.8286   
ABC Beauty College Inc                               0.4688   
AI Miami International University of Art and De...   0.3262   

                                                      MD_EARN_WNE_P10  \
INSTNM                                                                  
A & W Healthcare Educators                                        NaN   
A T Still University of Health Sciences                        219800   
ABC Beauty Academy                                                NaN   
ABC Beauty College Inc                              PrivacySuppressed   
AI Miami International University of Art and De...              29900   

                                                    GRAD_DEBT_MDN_SUPP  
INSTNM                                                                  
A & W Healthcare Educators                                     19022.5  
A T Still University of Health Sciences              PrivacySuppressed  
ABC Beauty Academy                                   PrivacySuppressed  
ABC Beauty College Inc                                           16500  
AI Miami International University of Art and De...               31000  

[5 rows x 26 columns]

In [ ]:
pd.options.display.max_rows = 6

In [ ]:
college.loc['Sp':'Su']

CITY STABBR  HBCU  MENONLY  \
INSTNM                                                                        
Spa Tech Institute-Ipswich                    Ipswich     MA   0.0      0.0   
Spa Tech Institute-Plymouth                  Plymouth     MA   0.0      0.0   
Spa Tech Institute-Westboro                  Westboro     MA   0.0      0.0   
...                                               ...    ...   ...      ...   
Stylemaster College of Hair Design           Longview     WA   0.0      0.0   
Styles and Profiles Beauty College             Selmer     TN   0.0      0.0   
Styletrends Barber and Hairstyling Academy  Rock Hill     SC   0.0      0.0   

                                            ...  PCTFLOAN  UG25ABV  \
INSTNM                                      ...                      
Spa Tech Institute-Ipswich                  ...    0.3906   0.7907   
Spa Tech Institute-Plymouth                 ...    0.4266   0.6250   
Spa Tech Institute-Westboro                 ...    0.4545   0.6882   
...                                         ...       ...      ...   
Stylemaster College of Hair Design          ...    0.7024   0.4510   
Styles and Profiles Beauty College          ...    0.7955   0.2400   
Styletrends Barber and Hairstyling Academy  ...    1.0000   0.3529   

                                              MD_EARN_WNE_P10  \
INSTNM                                                          
Spa Tech Institute-Ipswich                              21500   
Spa Tech Institute-Plymouth                             21500   
Spa Tech Institute-Westboro                             21500   
...                                                       ...   
Stylemaster College of Hair Design                      17000   
Styles and Profiles Beauty College          PrivacySuppressed   
Styletrends Barber and Hairstyling Academy  PrivacySuppressed   

                                            GRAD_DEBT_MDN_SUPP  
INSTNM                                                          
Spa Tech Institute-Ipswich                                6333  
Spa Tech Institute-Plymouth                               6333  
Spa Tech Institute-Westboro                               6333  
...                                                        ...  
Stylemaster College of Hair Design                       13320  
Styles and Profiles Beauty College           PrivacySuppressed  
Styletrends Barber and Hairstyling Academy              9495.5  

[201 rows x 26 columns]

In [ ]:
college = college.sort_index(ascending=False)
college.index.is_monotonic_decreasing

True

In [ ]:
college.loc['E':'B']

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
college.loc['E':'B']

## Indices

## Examining the index

In [ ]:
college = pd.read_csv('data/college.csv')
columns = college.columns
columns

In [ ]:
columns.values

In [ ]:
columns[5]

In [ ]:
columns[[1,8,10]]

In [ ]:
columns[-7:-4]

In [ ]:
columns.min(), columns.max(), columns.isnull().sum()

In [ ]:
columns + '_A'

In [ ]:
columns > 'G'

In [ ]:
columns[1] = 'city'

In [ ]:
c1 = columns[:4]
c1

In [ ]:
c2 = columns[2:5]
c2

In [ ]:
c1.union(c2)

In [ ]:
c1.symmetric_difference(c2)

## Producing Cartesian products

In [ ]:
s1 = pd.Series(index=list('aaab'), data=np.arange(4))
s1

In [ ]:
s2 = pd.Series(index=list('cababb'), data=np.arange(6))
s2

In [ ]:
s1 + s2

In [ ]:
(s1 + s2).index

In [ ]:
s1 = pd.Series(index=list('aaabb'), data=np.arange(5))
s2 = pd.Series(index=list('aaabb'), data=np.arange(5))
s1 + s2

In [ ]:
s1 = pd.Series(index=list('aaabb'), data=np.arange(5))
s2 = pd.Series(index=list('bbaaa'), data=np.arange(5))
s1 + s2

## Exploding Indexes

In [ ]:
employee = pd.read_csv('data/employee.csv', index_col='RACE')
employee.head()

In [ ]:
salary1 = employee['BASE_SALARY']
salary2 = employee['BASE_SALARY']
salary1 is salary2

In [ ]:
salary1 = employee['BASE_SALARY'].copy()
salary2 = employee['BASE_SALARY'].copy()
salary1 is salary2

In [ ]:
salary1.shape

In [ ]:
salary1 = salary1.sort_index()
salary1.head()

In [ ]:
salary2.head()

In [ ]:
salary_add = salary1 + salary2

In [ ]:
salary_add.head()

In [ ]:
salary_add.shape

In [ ]:
salary_add1 = salary1 + salary1
len(salary1), len(salary2), len(salary_add), len(salary_add1)

In [ ]:
index_vc = salary1.index.value_counts(dropna=False)
index_vc

In [ ]:
index_vc.pow(2).sum()

## Filling values with unequal indexes

In [ ]:
baseball_14 = pd.read_csv('data/baseball14.csv', index_col='playerID')
baseball_15 = pd.read_csv('data/baseball15.csv', index_col='playerID')
baseball_16 = pd.read_csv('data/baseball16.csv', index_col='playerID')
baseball_14.head()

In [ ]:
baseball_14.shape

In [ ]:
baseball_15.shape

In [ ]:
(baseball_15 + baseball_14).shape

In [ ]:
baseball_14.index.difference(baseball_15.index)

In [ ]:
hits_14 = baseball_14['H']
hits_15 = baseball_15['H']
hits_16 = baseball_16['H']
hits_14.head()

In [ ]:
(hits_14 + hits_15).head()

In [ ]:
hits_14.add(hits_15, fill_value=0).head()

In [ ]:
hits_total = hits_14.add(hits_15, fill_value=0).add(hits_16, fill_value=0)
hits_total.head()

In [ ]:
hits_total.hasnans

## How it works...

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd'], data=[np.nan, 3, np.nan, 1])
s

In [ ]:
s1 = pd.Series(index=['a', 'b', 'c'], data=[np.nan, 6, 10])
s1

In [ ]:
s.add(s1, fill_value=5)

In [ ]:
s1.add(s, fill_value=5)

## There's more

In [ ]:
df_14 = baseball_14[['G','AB', 'R', 'H']]
df_14.head()

In [ ]:
df_15 = baseball_15[['AB', 'R', 'H', 'HR']]
df_15.head()

In [ ]:
(df_14 + df_15).head(10).style.highlight_null('yellow')

In [ ]:
df_14.add(df_15, fill_value=0).head(10).style.highlight_null('yellow')